/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CLIENT_SECRET_VERIFIER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JACKSON_API_KEYS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXTAUTH_ADMIN_CREDENTIALS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXTAUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENID_RSA_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENID_RSA_PUBLIC_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OryPolis": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUBLIC_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StriveWeeklySES": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}